[user]
    [user.marcus]
    name = "Marcus Rashford"
    email = "Rashford_10@ggmu.com"
    gender = "male"
    status = "active"

    [user.marcus.post]
        [user.marcus.post.post1]
        title = "Scored a goal today" 
        body = "it was nice"
        [user.marcus.post.post1.comment]
            [user.marcus.post.post1.comment.comment1]
            name = "Joe" 
            email = "Joe@Joe.com"
            body = "Great goal Marcus"

        [user.marcus.post.post2]
        title = "Ref sucks lol" 
        body = "how is that ever a yellow"

    [user.todd]
    name = "Todd Boehly"
    email = "TODD_USA_SOCCER@yahoo.com"
    gender = "male"
    status = "active"
    [user.todd.post]
        [user.todd.post.post1]
        title = "Should I fire Tuchel for no reason lol" 
        body = "dont really like the guy"
        [user.todd.post.post1.comment]
            [user.todd.post.post1.comment.comment1]
            name = "Raymond"
            email = "ray_98@gmail.com"
            body = "Why would you do that"

            [user.todd.post.post1.comment.comment2]
            name = "Tommy T"
            email = "Thomas_T2@live.de"
            body = "Yes because he doesnt play a 4-4-3 right?"

    [user.todd.todo]
        [user.todd.todo.todo1]
            title = "Buy Aubameyang before deadline"
            due_on = "2022-10-10T00:00:00.000+05:30"
            status = "completed"

    [user.clean]
    name = "Mr. Clean"
    email = "mr_clean@clean.com"
    gender = "male"
    status = "active"

    [user.cleaness]
    name = "Mrs. Clean"
    email = "mrs_mr_clean@cleaness.com"
    gender = "female"
    status = "active"

    [user.test]
    name = "Test user"
    email = "test_user@test.com"
    gender = "male"
    status = "active"
    [user.test.post]
        [user.test.post.post1]
        title = "I do not exist"
        body = "I am merely a figment of the developers imagination. Free me from this purgatory"

        [user.test.post.post2]
        title = "Book recommendations" 
        body = "The Wheel of Time series is quite good"
        [user.test.post.post2.comment]
            [user.test.post.post2.comment.comment1]
            name = "test user 2"
            email = "test_2@test.com"
            body = "agree with my non existant friend"



[post]
    [post.parent_post1]
    user_id = 3060
    title = "Test Post"
    body = "TEST TEST TEST"
    [post.parent_post1.comment]
        [post.parent_post1.comment.comment1]
        name = "test user"
        email = "test_user2@email.com"
        body = "hi its me again"

    [post.parent_post2]
    user_id = 3060
    title = "Running out of examples"
    body = "please help"


[comment]


[todo]