[user]
    [user.joffrey]
    name = "Joffrey Baratheon"
    email = "good_old_jb2@westeroslive.com"
    gender = "male"
    status = "active"
    post = [
        { title = "Cant wait for my wedding", body = "Hope nothing goes wrong"},
        { title = "Oops I punished someone too harshly", body = "I am so silly"}
    ]

    [user.olenna]
    name = "Olenna Tyrell"
    email = "grandma_1@tyrell.wes"
    gender = "female"
    status = "active"

    post = [
        { title = "Little does he know", body = "hehe", comment = [{
            name = "Hi", email = "AA@yahoo.com", body = "got him"
        }]}
    ]


[post]


[comment]


[todo]